# Generated by Django 3.0 on 2020-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='static/img/a.jpg', null=True, upload_to='uploads/'),
        ),
    ]
