# Generated by Django 3.0 on 2020-12-08 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20201208_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('stitle', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('stitle1', models.CharField(blank=True, max_length=100)),
                ('content1', models.TextField(blank=True)),
                ('stitle2', models.CharField(blank=True, max_length=100)),
                ('content2', models.TextField(blank=True)),
                ('stitle3', models.CharField(blank=True, max_length=100)),
                ('content3', models.TextField(blank=True)),
                ('stitle4', models.CharField(blank=True, max_length=100)),
                ('content4', models.TextField(blank=True)),
                ('stitle5', models.CharField(blank=True, max_length=100)),
                ('content5', models.TextField(blank=True)),
                ('stitle6', models.CharField(blank=True, max_length=100)),
                ('content6', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userblog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
