# Generated by Django 3.0 on 2021-05-16 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210516_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='number',
        ),
        migrations.AddField(
            model_name='dogs',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
