# Generated by Django 3.0 on 2021-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210516_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='location',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana\t', 'Haryana\t'), ('Himachal', 'Himachal'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram aizawl', 'Mizoram aizawl'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab\t', 'Punjab\t'), ('Rajasthan', 'Rajasthan'), ('Sikkim\t', 'Sikkim\t'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura\t'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand ', 'Uttarakhand '), ('West Bengal', 'West Bengal')], default='green', max_length=30),
        ),
    ]
