# Generated by Django 3.0 on 2021-05-16 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_req'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogs',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='dogs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
